-- =================================================================================
-- DP-800 - HANDS-ON LAB: DATA ENCRYPTION (TDE, ALWAYS ENCRYPTED, AND CELL-LEVEL)
-- Database: AdventureWorks2025 (or similar)
-- =================================================================================
-- THEORY REFERENCE: ../../../certification/05-data-security-compliance/01-encryption.md
--    Open the theory guide alongside this lab for conceptual context.
-- =================================================================================
-- SETUP NOTE: To run this and other lab scripts, you need
-- to restore the AdventureWorks database backup (OLTP version) available at:
-- https://learn.microsoft.com/en-us/sql/samples/adventureworks-install-configure?view=sql-server-ver17&tabs=ssms
-- =================================================================================
-- This script demonstrates all encryption types covered in the study guide:
--   1. Transparent Data Encryption (TDE): Protecting files on disk (DEK and sys.dm_database_encryption_keys)
--   2. Always Encrypted (local CMK): DETERMINISTIC vs RANDOMIZED encryption
--   3. Always Encrypted with Secure Enclaves: range/LIKE query scenario
--   4. Cell-Level Encryption: Master Key, Certificate, Symmetric Key (ENCRYPTBYKEY/DECRYPTBYKEY)
--   5. Column Encryption Key Rotation (Metadata-Only vs Full Data Re-encryption)
--   6. Practical Project Scenarios (Protecting Medical Records and Credit Cards)
-- =================================================================================

USE AdventureWorks2025;
GO

-- Preventive cleanup
-- WARNING: this lab creates keys and encrypted objects in the selected database.
-- Use a disposable database. Never reuse a production password or certificate.
IF EXISTS (SELECT * FROM sys.symmetric_keys WHERE name = 'LabSymKey')
    CLOSE SYMMETRIC KEY LabSymKey;

IF EXISTS (SELECT * FROM sys.symmetric_keys WHERE name = 'LabSymKey')
    DROP SYMMETRIC KEY LabSymKey;

IF EXISTS (SELECT * FROM sys.certificates WHERE name = 'LabCellCert')
    DROP CERTIFICATE LabCellCert;

DROP TABLE IF EXISTS lab.EncryptedUserData;
DROP TABLE IF EXISTS lab.EncryptedCellData;
GO

-- Table structure for testing
CREATE TABLE lab.EncryptedCellData (
    UserID INT IDENTITY(1,1) PRIMARY KEY,
    UserName NVARCHAR(100) NOT NULL,
    EncryptedCreditCard VARBINARY(MAX) NULL
);
GO


-- =================================================================================
-- PART 0: OPTIONAL PREREQUISITE - CREATE A LOCAL ALWAYS ENCRYPTED KEY
-- =================================================================================
-- Use this tutorial if you do not have Azure Key Vault or another external key store.
-- The certificate is created in the Windows certificate store of the CURRENT USER.
-- Do not commit or share the private key. Use a disposable lab certificate only.
--
-- 1) Run once in Windows PowerShell (not in the SQL query window):
--
--   $cert = New-SelfSignedCertificate `
--     -Subject "CN=DP800-Lab-CMK" `
--     -CertStoreLocation "Cert:\CurrentUser\My" `
--     -KeySpec KeyExchange `
--     -KeyLength 2048 `
--     -KeyAlgorithm RSA `
--     -HashAlgorithm SHA256 `
--     -KeyExportPolicy Exportable
--   $cert.Thumbprint
--
-- 2) Copy the thumbprint returned above (remove spaces) and replace <THUMBPRINT>
--    in the CREATE COLUMN MASTER KEY statement below. Execute it in this database.
-- 3) In SSMS, with the Always Encrypted wizard enabled, create the CEK:
--      Database > Security > Always Encrypted Keys > Column Encryption Keys
--      New Column Encryption Key > name it LabLocalCEK > select LabLocalCMK.
--    SSMS performs the client-side RSA encryption that produces ENCRYPTED_VALUE;
--    this value cannot be safely invented or generated by plain T-SQL.
-- 4) After the CEK exists, execute PART 2. Connect with:
--      Column Encryption Setting=enabled
--    and use the same Windows user that owns the certificate.
--
-- Optional verification in PowerShell:
--   Get-ChildItem Cert:\CurrentUser\My | Where-Object Subject -eq 'CN=DP800-Lab-CMK'

-- CREATE COLUMN MASTER KEY LabLocalCMK
-- WITH (
--     KEY_STORE_PROVIDER_NAME = 'MSSQL_CERTIFICATE_STORE',
--     KEY_PATH = 'CurrentUser/My/<THUMBPRINT>'
-- );
-- GO

-- =================================================================================
-- PART 1: CELL-LEVEL ENCRYPTION (MASTER KEY, CERTIFICATE, AND SYMMETRIC KEY)
-- =================================================================================
-- KEY CONCEPTS AND DEFINITIONS:
--   - CELL-LEVEL ENCRYPTION: Manual cell-level encryption executed via T-SQL.
--   - HIERARCHY: Database Master Key (DMK) -> Certificate -> Symmetric Key (AES_256).
--   - FUNCTIONS: `ENCRYPTBYKEY(KEY_GUID('KeyName'), Text)` to encrypt and
--     `DECRYPTBYKEY(BinaryData)` to decrypt.

-- 1. Create Database Master Key (if it doesn't exist)
IF NOT EXISTS (SELECT * FROM sys.symmetric_keys WHERE name = '##DatabaseMasterKey##')
BEGIN
    -- Replace the placeholder before execution; do not commit the real password.
    CREATE MASTER KEY ENCRYPTION BY PASSWORD = '<REPLACE_WITH_UNIQUE_LAB_PASSWORD>';
END
GO

-- 2. Create Certificate to protect the Symmetric Key
CREATE CERTIFICATE LabCellCert 
WITH SUBJECT = 'Certificado de Protecao de Celulas';
GO

-- 3. Create Symmetric Key protected by the Certificate
CREATE SYMMETRIC KEY LabSymKey
WITH ALGORITHM = AES_256
ENCRYPTION BY CERTIFICATE LabCellCert;
GO

-- -- [DP-800 EXAM TIP]
-- 4. Insert data encrypted via ENCRYPTBYKEY (server-side/manual encryption)
OPEN SYMMETRIC KEY LabSymKey DECRYPTION BY CERTIFICATE LabCellCert;

INSERT INTO lab.EncryptedCellData (UserName, EncryptedCreditCard)
VALUES (N'Alice Smith', ENCRYPTBYKEY(KEY_GUID('LabSymKey'), N'4532-1111-2222-3333'));

CLOSE SYMMETRIC KEY LabSymKey;
GO

-- 5. Read data decrypted via DECRYPTBYKEY
OPEN SYMMETRIC KEY LabSymKey DECRYPTION BY CERTIFICATE LabCellCert;

SELECT 
    UserID,
    UserName,
    EncryptedCreditCard AS CartaoCriptografadoBinario,
    CONVERT(NVARCHAR(50), DECRYPTBYKEY(EncryptedCreditCard)) AS CartaoDescriptografado
FROM lab.EncryptedCellData;

CLOSE SYMMETRIC KEY LabSymKey;
GO


-- =================================================================================
-- PART 2: ALWAYS ENCRYPTED (DETERMINISTIC VS RANDOMIZED AND CMK/CEK HIERARCHY)
-- =================================================================================
-- KEY CONCEPTS AND DEFINITIONS:
--   - ALWAYS ENCRYPTED: Client-side encryption. The database NEVER sees data in plaintext.
--   - CMK (Column Master Key): Master key stored in an external key repository (e.g., Azure Key Vault / Windows Cert Store).
--   - CEK (Column Encryption Key): Key encrypted by the CMK that protects the column data.
--   - DETERMINISTIC: Same plaintext always generates the same ciphertext. Allows `=`, `JOIN`, `GROUP BY`.
--   - RANDOMIZED: Same plaintext generates different ciphertext on each write. Higher security; does NOT allow direct comparisons.
--   - SECURE ENCLAVES (VBS): Enables range queries (`BETWEEN`, `<`, `>`) and `LIKE` on RANDOMIZED columns.

-- After completing PART 0, execute this DDL. It requires the LabLocalCEK created
-- by SSMS and a connection using Column Encryption Setting=enabled.
/*
CREATE TABLE lab.AlwaysEncryptedPatients (
    PatientID INT PRIMARY KEY,
    -- DETERMINISTIC: Allows searching by exact SSN (= '123-45-6789')
    SSN CHAR(11) COLLATE Latin1_General_BIN2 
        ENCRYPTED WITH (
            COLUMN_ENCRYPTION_KEY = LabLocalCEK,
            ENCRYPTION_TYPE = DETERMINISTIC,
            ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256'
        ) NOT NULL,
    -- RANDOMIZED: No comparisons without Secure Enclaves
    Salary MONEY 
        ENCRYPTED WITH (
            COLUMN_ENCRYPTION_KEY = LabLocalCEK,
            ENCRYPTION_TYPE = RANDOMIZED,
            ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256'
        ) NULL
);

-- Use the Always Encrypted-enabled client to insert and query these values.
INSERT INTO lab.AlwaysEncryptedPatients (PatientID, SSN, Salary)
VALUES (1, '123-45-6789', 85000.00),
       (2, '123-45-6789', 92000.00);

-- DETERMINISTIC: equality works because equal plaintexts have equal ciphertext.
SELECT PatientID, SSN
FROM lab.AlwaysEncryptedPatients
WHERE SSN = '123-45-6789';

-- RANDOMIZED: direct equality/range predicates are not supported without an enclave.
SELECT PatientID, Salary
FROM lab.AlwaysEncryptedPatients
WHERE Salary > 80000.00;
*/
GO


-- =================================================================================
-- PART 3: ALWAYS ENCRYPTED WITH SECURE ENCLAVE (RANDOMIZED + RANGE/LIKE)
-- =================================================================================
-- This is an optional, configuration-dependent example. It requires Azure SQL
-- Database/SQL Managed Instance or a supported SQL Server deployment, a CEK
-- configured for enclave computations, driver support, and enclave attestation.
-- The encrypted column remains RANDOMIZED, but the enclave can evaluate predicates
-- such as BETWEEN and LIKE without exposing plaintext to the SQL engine.
/*
-- The CEK must be created/configured through SSMS or the supported client tooling.
CREATE TABLE lab.EnclavePatients (
    PatientID INT PRIMARY KEY,
    BirthDate DATE ENCRYPTED WITH (
        COLUMN_ENCRYPTION_KEY = LabLocalCEK,
        ENCRYPTION_TYPE = RANDOMIZED,
        ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256'
    ) NOT NULL
);

-- Run from an enclave-enabled client connection, not plain T-SQL in SSMS.
SELECT PatientID, BirthDate
FROM lab.EnclavePatients
WHERE BirthDate BETWEEN '1980-01-01' AND '1989-12-31';
*/
GO


-- =================================================================================
-- PART 4: TRANSPARENT DATA ENCRYPTION (TDE) AND STATUS INSPECTION
-- =================================================================================
-- KEY CONCEPTS AND DEFINITIONS:
--   - TDE: Encrypts data files (.mdf) and log (.ldf) at rest. Transparent to applications.
--   - Azure SQL Database: TDE is enabled by default.
--   - sys.dm_database_encryption_keys: Dynamic management view to inspect encryption state (3 = Encrypted).

-- -- [DP-800 EXAM TIP]
-- Query TDE status on server databases
SELECT 
    db_name(database_id) AS DatabaseName,
    encryption_state,
    CASE encryption_state
        WHEN 0 THEN 'Sem Chave DEK'
        WHEN 1 THEN 'Não Criptografado'
        WHEN 2 THEN 'Criptografia em Andamento'
        WHEN 3 THEN 'CRIPTOGRAFADO (TDE Ativo)'
        WHEN 4 THEN 'Troca de Chave em Andamento'
        WHEN 5 THEN 'Descriptografia em Andamento'
    END AS StatusCriptografia,
    key_algorithm,
    key_length
FROM sys.dm_database_encryption_keys;
GO

-- Optional TDE activation for a self-managed SQL Server lab.
-- Run only with appropriate privileges; Azure SQL Database normally has TDE enabled.
/*
USE master;
CREATE MASTER KEY ENCRYPTION BY PASSWORD = 'Use-A-Unique-Lab-Password!';
CREATE CERTIFICATE LabTDECert WITH SUBJECT = 'DP-800 lab TDE certificate';
USE AdventureWorks2025;
CREATE DATABASE ENCRYPTION KEY
WITH ALGORITHM = AES_256
ENCRYPTION BY SERVER CERTIFICATE LabTDECert;
ALTER DATABASE AdventureWorks2025 SET ENCRYPTION ON;
GO
*/


-- =================================================================================
-- PART 5: PRACTICAL PROJECT SCENARIOS
-- =================================================================================

-- SCENARIO 1: Encryption Decision Matrix for Compliance (LGPD / HIPAA / PCI-DSS)
-- Mapping of protected tables and their respective encryption mechanisms in production.

SELECT 
    'TDE' AS Tecnologia,
    'Dados em Repouso (Discos/Backups)' AS AlvoProtecao,
    'DBA possui acesso aos dados em memória' AS EscopoSeguranca,
    'Zero impacto em consultas' AS SuporteQueries
UNION ALL
SELECT 
    'Always Encrypted (Deterministic)',
    'Colunas PII sensíveis (Ex: CPF/SSN)',
    'DBA NÃO vê texto claro. Permite busca por igualdade (=)',
    'Permite =, JOIN, GROUP BY'
UNION ALL
SELECT 
    'Always Encrypted + Enclave (Randomized)',
    'Dados altamente confidenciais com busca por intervalo',
    'Processamento isolado via VBS Enclave no servidor',
    'Permite BETWEEN, <, >, LIKE'
UNION ALL
SELECT 
    'Cell-Level (ENCRYPTBYKEY)',
    'Células específicas em colunas legadas',
    'Requer código manual OPEN/CLOSE SYMMETRIC KEY',
    'Exige chamadas explícitas de função';
GO

-- =================================================================================================
-- NEXT STEP: Review the theory at ../../../certification/05-data-security-compliance/01-encryption.md
-- =================================================================================================
