-- =================================================================================
-- DP-800 - PRACTICAL LAB: GITHUB COPILOT, COPILOT IN FABRIC AND PROJECT RULES
-- Database: AdventureWorks2025 (or similar)
-- =================================================================================
-- THEORY REFERENCE: ../../../certification/04-ai-assisted-tools/02-github-copilot-setup.md
--    Open the theory guide alongside this lab for conceptual context.
-- =================================================================================
-- SETUP NOTE: To run this and other lab scripts, you need to
-- restore the AdventureWorks database backup (OLTP version) available at:
-- https://learn.microsoft.com/en-us/sql/samples/adventureworks-install-configure?view=sql-server-ver17&tabs=ssms
-- =================================================================================
-- SAFETY: This lab creates and replaces objects in the selected database. Run it in
-- a disposable lab database with synthetic data only. GitHub Copilot configuration,
-- repository instructions, content exclusions, and secret scanning are exercised
-- outside SQL (in the repository/editor); this script validates the database-side
-- review and execution safeguards.
-- This script demonstrates validations and best practices when incorporating GitHub Copilot into the project:
--   1. Fixing Unsafe Patterns Generated by AI: Replacing Concatenation with `sp_executesql`
--   2. Compliance with Repository Instructions (`.github/copilot-instructions.md`)
--   3. Pre-Production Validation of Suggested T-SQL Scripts
--   4. Standard Stored Procedure Structure (SET NOCOUNT ON, THROW, TRY/CATCH)
--   5. Practical Project Scenarios (Code Review Checklist for AI Suggestions)
-- =================================================================================

USE AdventureWorks2025;
GO

-- Preventive cleanup
IF EXISTS (SELECT * FROM sys.procedures WHERE name = 'usp_SearchProductsSecure' AND schema_id = SCHEMA_ID('lab'))
    DROP PROCEDURE lab.usp_SearchProductsSecure;

DROP TABLE IF EXISTS lab.ProductsCatalog;
GO

-- Table structure for testing
CREATE TABLE lab.ProductsCatalog (
    ProductID INT IDENTITY(1,1) PRIMARY KEY,
    ProductName NVARCHAR(100) NOT NULL,
    Category NVARCHAR(50) NOT NULL,
    Price DECIMAL(18,2) NOT NULL
);
GO

INSERT INTO lab.ProductsCatalog (ProductName, Category, Price) VALUES 
('Notebook Pro', 'Eletrônicos', 4500.00),
('Mouse Sem Fio', 'Acessórios', 150.00),
('Teclado Mecânico', 'Acessórios', 350.00);
GO


-- =================================================================================
-- PART 1: VALIDATION OF DYNAMIC SQL SUGGESTED BY AI (UNSAFE VS SAFE)
-- =================================================================================
-- KEY CONCEPTS AND DEFINITIONS:
--   - SQL INJECTION RISK IN AI: Language models may suggest direct string concatenations when generating dynamic SQL.
--   - SAFE PATTERN: Use `sp_executesql` with typed parameters.

DECLARE @CategoryInput NVARCHAR(100) = N'Acessórios';

-- -- [DP-800 EXAM TIP]
-- 1. Unsafe Pattern (Often suggested by AI): String Concatenation
-- DECLARE @sqlInseguro NVARCHAR(MAX) = N'SELECT * FROM lab.ProductsCatalog WHERE Category = ''' + @CategoryInput + N'''';
-- EXEC(@sqlInseguro); -- VULNERABLE TO SQL INJECTION!

-- 2. Safe Pattern (Mandatory in production): Parameterized sp_executesql
DECLARE @sqlSeguro NVARCHAR(MAX) = N'SELECT ProductID, ProductName, Price FROM lab.ProductsCatalog WHERE Category = @CategoryParam';
EXEC sp_executesql 
    @stmt = @sqlSeguro,
    @params = N'@CategoryParam NVARCHAR(50)',
    @CategoryParam = @CategoryInput;
GO


-- =================================================================================
-- PART 2: COMPLIANCE WITH .GITHUB/COPILOT-INSTRUCTIONS.MD RULES
-- =================================================================================
-- KEY CONCEPTS AND DEFINITIONS:
--   - COPILOT INSTRUCTIONS: File located at the root in `.github/copilot-instructions.md`.
--     Defines rules such as: mandatory `SET NOCOUNT ON`, use `THROW` instead of `RAISERROR`,
--     2-part schema prefixes (`lab.TableName`) and strict transaction management in CATCH.

-- -- [DP-800 EXAM TIP]
-- Stored Procedure structured in 100% compliance with the institutional guide
CREATE PROCEDURE lab.usp_SearchProductsSecure
    @CategoryName NVARCHAR(50)
AS
BEGIN
    -- Rule 1: SET NOCOUNT ON mandatory
    SET NOCOUNT ON;

    -- Rule 2: Robust error handling with TRY/CATCH and THROW
    BEGIN TRY
        IF @CategoryName IS NULL OR LEN(TRIM(@CategoryName)) = 0
            -- Rule 3: Use THROW instead of RAISERROR
            THROW 50001, 'O nome da categoria não pode ser nulo ou vazio.', 1;

        -- Rule 4: 2-part table names (lab.ProductsCatalog)
        SELECT 
            ProductID,
            ProductName,
            Category,
            Price
        FROM lab.ProductsCatalog
        WHERE Category = @CategoryName;
    END TRY
    BEGIN CATCH
        -- Handle and re-throw the error maintaining original details
        IF XACT_STATE() <> 0
            ROLLBACK TRANSACTION;
        THROW;
    END CATCH;
END;
GO

-- Test valid execution
EXEC lab.usp_SearchProductsSecure @CategoryName = N'Eletrônicos';
GO

-- Test execution with error handled via THROW
BEGIN TRY
    EXEC lab.usp_SearchProductsSecure @CategoryName = N'';
END TRY
BEGIN CATCH
    PRINT 'ERRO DE CAPTURA DO COPILOT INSTRUCTIONS: ' + ERROR_MESSAGE();
END CATCH;
GO


-- =================================================================================
-- PART 3: PRACTICAL PROJECT SCENARIOS
-- =================================================================================

--- SCENARIO 1: Pre-Production Validation Checklist for AI Suggestions
-- Runs stress tests and type auditing before approving the PR of suggested code.

SELECT 
    p.name AS ProcedureName,
    m.definition AS StatementText,
    CASE 
        WHEN m.definition LIKE '%EXEC(%' OR m.definition LIKE '%EXECUTE(%' THEN 'VULNERÁVEL (Dynamic SQL Bruto)'
        WHEN m.definition LIKE '%RAISERROR%' THEN 'DEPRECADO (Usar THROW)'
        WHEN m.definition NOT LIKE '%SET NOCOUNT ON%' THEN 'AVISO (Falta SET NOCOUNT ON)'
        ELSE 'CONFORME'
    END AS StatusConformidadeCopilot
FROM sys.procedures p
JOIN sys.sql_modules m ON p.object_id = m.object_id
WHERE p.schema_id = SCHEMA_ID('lab');
GO

-- =================================================================================================
-- NEXT STEP: Review the theory at ../../../certification/04-ai-assisted-tools/02-github-copilot-setup.md
-- =================================================================================================
