-- =================================================================================
-- DP-800 - HANDS-ON LAB: TABLE AND INDEX PARTITIONING
-- Database: AdventureWorks2025 (or similar)
-- =================================================================================
-- SETUP NOTE: To run this and other lab scripts, you need
-- to restore the AdventureWorks database backup (OLTP version) available at:
-- https://learn.microsoft.com/en-us/sql/samples/adventureworks-install-configure?view=sql-server-ver17&tabs=ssms
-- =================================================================================
-- This script demonstrates the creation, management, and optimization of partitioned tables and
-- indexes in SQL Server, covering:
--   1. Creating a Partition Function (RANGE RIGHT) and Partition Scheme
--   2. Creating partitioned tables and aligned indexes
--   3. Querying Partitions via DMV and the $PARTITION system function
--   4. Partition Elimination in the execution plan
--   5. Instant archival operation: Partition Switching (SWITCH OUT)
--   6. Sliding Window Cycle: SPLIT, MERGE, and NEXT USED
-- =================================================================================

USE AdventureWorks2025;
GO

-- Preventive cleanup in case the script is run more than once
DROP TABLE IF EXISTS lab.OrdersPartitionedStaging;
DROP TABLE IF EXISTS lab.OrdersPartitionedHistory;
DROP TABLE IF EXISTS lab.OrdersPartitioned;
IF EXISTS (SELECT * FROM sys.partition_schemes WHERE name = 'PS_OrdersByYear')
    DROP PARTITION SCHEME PS_OrdersByYear;
IF EXISTS (SELECT * FROM sys.partition_functions WHERE name = 'PF_OrdersByYear')
    DROP PARTITION FUNCTION PF_OrdersByYear;
GO


-- =================================================================================
-- PART 1: CREATING THE PARTITIONING STRUCTURE (FUNCTION AND SCHEME)
-- =================================================================================
-- KEY CONCEPTS AND DEFINITIONS:
--   - TABLE PARTITIONING: Technique for physically dividing tables and indexes into smaller, manageable
--     segments (partitions) in the database, while maintaining the logical relational view as a single table for the application.
--     It significantly improves scan performance and maintainability of large data volumes.
--   - PARTITION FUNCTION: Defines the logical data division rule based on a partition key
--     and specific boundary values, mapping whether boundaries belong to the left or right side.
--   - RANGE RIGHT VS RANGE LEFT:
--     * RANGE RIGHT: The boundary value (e.g., '2025-01-01') is the minimum value of the right-side range (data >= boundary).
--       It is the most intuitive and recommended pattern for date partitions (e.g., 2025 data starts exactly on 01/01).
--     * RANGE LEFT: The boundary value belongs to the left-side range (data <= boundary).
--   - PARTITION SCHEME: Maps the logical partitions generated by the Partition Function
--     to different physical database filegroups (allowing I/O distribution across different disks).
--   - ALIGNED INDEXES: Indexes that share the same Partition Scheme and Partition Key as the base table.
--     Perfect alignment of all indexes is a mandatory requirement for enabling the Partition Switching command.

-- 1. Create the Partition Function (RANGE RIGHT for date groupings)
-- RANGE RIGHT: The specified boundary value belongs to the partition on the right (>= value).
-- Boundary values: 2024-01-01, 2025-01-01, 2026-01-01.
-- This creates 4 partitions:
--   Partition 1: values < '2024-01-01'
--   Partition 2: values >= '2024-01-01' and < '2025-01-01'
--   Partition 3: values >= '2025-01-01' and < '2026-01-01'
--   Partition 4: values >= '2026-01-01'
CREATE PARTITION FUNCTION PF_OrdersByYear (DATE)
AS RANGE RIGHT FOR VALUES (
    '2024-01-01', 
    '2025-01-01', 
    '2026-01-01'
);
GO

-- 2. Create the Partition Scheme
-- Mapping all partitions to the PRIMARY filegroup (to simplify the lab).
-- In production, it is common to map to different disk filegroups for I/O gains.
CREATE PARTITION SCHEME PS_OrdersByYear
AS PARTITION PF_OrdersByYear ALL TO ([PRIMARY]);
GO

-- 3. Create the Partitioned Table referencing the Scheme
-- Important: The partitioning key (OrderDate) MUST be part of the composite primary key.
CREATE TABLE lab.OrdersPartitioned (
    OrderID INT NOT NULL,
    OrderDate DATE NOT NULL,
    CustomerID INT NOT NULL,
    TotalAmount DECIMAL(18,2) NOT NULL,
    CONSTRAINT PK_OrdersPartitioned PRIMARY KEY CLUSTERED (OrderDate, OrderID)
) ON PS_OrdersByYear (OrderDate); -- Partitioned table here
GO

-- 4. Create an ALIGNED Non-Clustered Index
-- An index is "aligned" when it is created on the same Partition Scheme as the base table.
-- This is a mandatory prerequisite for Partition Switching operations.
CREATE NONCLUSTERED INDEX IX_OrdersPartitioned_CustomerID
ON lab.OrdersPartitioned(CustomerID)
ON PS_OrdersByYear (OrderDate); -- Aligned!
GO


-- =================================================================================
-- PART 2: QUERYING METADATA AND THE $PARTITION FUNCTION
-- =================================================================================

-- 1. Populate test data for different years
INSERT INTO lab.OrdersPartitioned (OrderID, OrderDate, CustomerID, TotalAmount)
VALUES 
(1, '2023-11-15', 101, 150.00), -- Partition 1 (< 2024)
(2, '2024-05-10', 102, 350.00), -- Partition 2 (2024)
(3, '2024-12-31', 103, 720.00), -- Partition 2 (2024)
(4, '2025-02-28', 101, 110.00), -- Partition 3 (2025)
(5, '2026-07-20', 104, 500.00); -- Partition 4 (>= 2026)
GO

-- 2. Discover which partition a given value belongs to using the $PARTITION function
SELECT 
    $PARTITION.PF_OrdersByYear('2023-11-15') AS Particao_Registro_1,
    $PARTITION.PF_OrdersByYear('2024-12-31') AS Particao_Registro_3,
    $PARTITION.PF_OrdersByYear('2026-01-01') AS Particao_Registro_5;
GO

-- 3. View partitions, row counts, and ranges via metadata DMV
SELECT 
    p.partition_number AS NumeroParticao,
    p.rows AS QuantidadeLinhas,
    prv.value AS LimiteValorSuperior
FROM sys.partitions p
JOIN sys.indexes i
    ON i.object_id = p.object_id
   AND i.index_id = p.index_id
JOIN sys.partition_schemes ps
    ON ps.data_space_id = i.data_space_id
JOIN sys.partition_functions pf
    ON pf.function_id = ps.function_id
LEFT JOIN sys.partition_range_values prv 
    ON prv.function_id = pf.function_id 
    AND prv.boundary_id = p.partition_number
WHERE pf.name = 'PF_OrdersByYear' AND p.index_id <= 1
ORDER BY p.partition_number;
GO


-- =================================================================================
-- PART 3: PARTITION ELIMINATION
-- =================================================================================
-- KEY CONCEPTS AND DEFINITIONS:
--   - PARTITION ELIMINATION: Crucial optimization where the query engine,
--     when analyzing query filters (WHERE clause), identifies the partitions containing the desired rows
--     and physically accesses ONLY those partitions, discarding the rest. Reduces I/O and speeds up searches.
--   - ELIMINATION BLOCKERS (Bottlenecks): The query optimizer cannot apply this simplification,
--     forcing a full scan of all partitions (Partition Scan), if:
--     1. The filter uses functions on the partition key column (e.g., `WHERE YEAR(OrderDate) = 2025` instead of `WHERE OrderDate >= '2025-01-01'`).
--     2. A function or conversion is applied to the partitioned column itself (e.g., `WHERE YEAR(OrderDate) = 2025`).
--        A function applied to the searched value, such as `OrderDate >= CAST(GETDATE() AS date)`, does not
--        automatically prevent elimination; always confirm the plan.
--     3. Implicit conversions occur on the partition key, preventing the predicate from being sargable.

SET STATISTICS IO ON;
GO

-- Test 1: Query filtering by the Partition Key (OrderDate)
-- EXECUTION PLAN: Check the Clustered Index Seek properties.
-- In the "Partitions Accessed" field, you will see a fixed range like "3..3" (accessed only the 2025 partition).
SELECT OrderID, CustomerID, TotalAmount 
FROM lab.OrdersPartitioned
WHERE OrderDate = '2025-02-28';
GO

-- Test 2: Query filtering by another column without the partition key
-- EXECUTION PLAN: The optimizer must scan all partitions looking for the ID.
-- In the "Partitions Accessed" field, the range will be "1..4" (Full Partition Scan).
SELECT OrderID, CustomerID, TotalAmount 
FROM lab.OrdersPartitioned
WHERE CustomerID = 101;
GO

SET STATISTICS IO OFF;
GO


-- =================================================================================
-- PART 4: PARTITION SWITCHING (ARCHIVING AND LOADING IN MILLISECONDS)
-- =================================================================================
-- KEY CONCEPTS AND DEFINITIONS:
--   - PARTITION SWITCHING: A metadata-only operation, typically very fast,
--     used to move entire data blocks from one table/partition to another. The engine only changes the physical page
--     allocation pointers in the SQL Server data dictionary, without physically moving rows.
--     However, it still requires schema locks and can block or be blocked; do not treat it as zero-downtime guarantee.
--   - STRICT SWITCH REQUIREMENTS AND RULES:
--     1. Source and target tables must have identical structures (same columns, data types, nullability, and constraints).
--     2. All indexes (both the main Clustered and NCIs) must be aligned on the same Partition Scheme.
--     3. The target partition or table must be completely empty (TRUNCATE).
--     4. Both source and target tables or partitions must reside on the same physical Filegroup.

-- 1. Create the History Table (Destination for archiving Partition 2 - Year 2024)
-- Must be aligned on the same partition scheme and have the same constraints/indexes.
CREATE TABLE lab.OrdersPartitionedHistory (
    OrderID INT NOT NULL,
    OrderDate DATE NOT NULL,
    CustomerID INT NOT NULL,
    TotalAmount DECIMAL(18,2) NOT NULL,
    CONSTRAINT PK_OrdersPartitionedHistory PRIMARY KEY CLUSTERED (OrderDate, OrderID)
) ON PS_OrdersByYear (OrderDate);

CREATE NONCLUSTERED INDEX IX_OrdersPartitionedHistory_CustomerID
ON lab.OrdersPartitionedHistory(CustomerID)
ON PS_OrdersByYear (OrderDate);
GO

-- 2. Execute SWITCH OUT of Partition 2 (2024 Data) to the history table
-- Notice this is instantaneous and free of write locks on disk for the rows!
ALTER TABLE lab.OrdersPartitioned
SWITCH PARTITION 2 TO lab.OrdersPartitionedHistory PARTITION 2;
GO

-- 3. Verify the result: the 2024 data has disappeared from the active table and is in the history.
SELECT 'Ativa (2024 removida)' AS Tabela, OrderID, OrderDate FROM lab.OrdersPartitioned
UNION ALL
SELECT 'Histórico (Apenas 2024)', OrderID, OrderDate FROM lab.OrdersPartitionedHistory;
GO


-- =================================================================================
-- PART 5: SLIDING WINDOW - SPLIT AND MERGE
-- =================================================================================
-- KEY CONCEPTS AND DEFINITIONS:
--   - SLIDING WINDOW: A temporal data administration technique to keep only data
--     from a recent period active (e.g., always keep the last 3 years active). Periodically, we remove
--     the oldest year (MERGE) and create a range for the incoming year (SPLIT).
--   - SPLIT: A Partition Function command that creates a new boundary, splitting an existing
--     partition into two. Before SPLIT, confirm that each dependent partition scheme already has a `NEXT USED`
--     filegroup; execute `ALTER PARTITION SCHEME ... NEXT USED` only when this is not already set.
--   - MERGE: A command that removes a partition boundary, merging two adjacent partitions into one.
--   - PHYSICAL DATA MOVEMENT: If we execute a SPLIT on a partition that already has data written,
--     or a MERGE merging partitions that contain active rows, SQL Server will be forced to physically move the rows
--     on disk to align with the new partition logic. This generates extensive table locks, consumes a lot of transaction log,
--     and can freeze the database. **Always empty the partition (via SWITCH or TRUNCATE) before MERGE, and execute SPLIT only on empty segments.**

-- 1. Define which Filegroup will receive the new boundary created by SPLIT.
-- In an environment with multiple schemes, confirm the NEXT USED of each one.
ALTER PARTITION SCHEME PS_OrdersByYear
NEXT USED [PRIMARY];
GO

-- 2. Execute SPLIT to create a new future data partition (Year 2027)
-- Logical boundary: 2027-01-01
ALTER PARTITION FUNCTION PF_OrdersByYear()
SPLIT RANGE ('2027-01-01');
GO

-- 3. Execute MERGE to merge old empty partitions
-- Merge the partition corresponding to '2024-01-01'
ALTER PARTITION FUNCTION PF_OrdersByYear()
MERGE RANGE ('2024-01-01');
GO

-- 4. Check the new partition metadata configuration
-- Note that the partition numbers and boundaries have been adjusted instantly.
SELECT 
    p.partition_number AS NumeroParticao,
    p.rows AS QuantidadeLinhas,
    prv.value AS LimiteValorSuperior
FROM sys.partitions p
JOIN sys.indexes i
    ON i.object_id = p.object_id
   AND i.index_id = p.index_id
JOIN sys.partition_schemes ps
    ON ps.data_space_id = i.data_space_id
JOIN sys.partition_functions pf
    ON pf.function_id = ps.function_id
LEFT JOIN sys.partition_range_values prv 
    ON prv.function_id = pf.function_id 
    AND prv.boundary_id = p.partition_number
WHERE pf.name = 'PF_OrdersByYear' AND p.index_id <= 1
ORDER BY p.partition_number;
GO


-- =================================================================================
-- PART 6: ADDITIONAL PRACTICAL SCENARIOS (RANGE LEFT VS RIGHT AND NON-ALIGNED INDEXES)
-- =================================================================================

-- 1. Testing the partition difference for the exact boundary date '2025-01-01'.
-- In RANGE RIGHT, the boundary belongs to the right-side partition; in RANGE LEFT, to the left-side.
-- After SPLIT/MERGE, physical partition numbers may change. Validate with $PARTITION, not by assumption.
SELECT 
    '2025-01-01' AS DataLimite,
    $PARTITION.PF_OrdersByYear('2025-01-01') AS ParticaoRangeRight;
GO

-- 2. Demonstration of SWITCH Blocking due to NON-ALIGNED Index
-- Create a non-aligned index (saved in the [PRIMARY] filegroup without referencing the partition key)
CREATE NONCLUSTERED INDEX IX_OrdersPartitioned_NonAligned
ON lab.OrdersPartitioned(TotalAmount)
ON [PRIMARY]; -- NOT ALIGNED!
GO

-- Attempt SWITCH with non-aligned index (Should fail with error 7733)
BEGIN TRY
    ALTER TABLE lab.OrdersPartitioned
    SWITCH PARTITION 3 TO lab.OrdersPartitionedHistory PARTITION 3;
END TRY
BEGIN CATCH
    PRINT 'ERRO ESPERADO SWITCH COM ÍNDICE NÃO ALINHADO: ' + ERROR_MESSAGE();
    -- Message: "ALTER TABLE SWITCH statement failed because index... is not partitioned..."
END CATCH;
GO

-- Solution: Remove the non-aligned index or recreate it as aligned
DROP INDEX IX_OrdersPartitioned_NonAligned ON lab.OrdersPartitioned;
GO
